#!/bin/sh
#
#  Copyright 2019 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################
# BleemSync Bootloader - CLOSED SOURCE (to prevent people from fucking it up)
# If someone knows how to open the payload and extract this file then
# hopefully they know what to modify and what not to modify!
# ModMyClassic.com / https://discordapp.com/invite/8gygsrw
###############################################################################

killall -s KILL sonyapp showLogo ui_menu

systemctl stop ftp.socket
systemctl stop telnet.socket
systemctl stop bleemsync.service
systemctl stop ssh.service
mount -o remount,rw /
# Link original blkid
ln -sf /bin/busybox.nosuid /sbin/blkid
# Remove binaries
rm -f /usr/bin/{busybox-bs,bleemsync_service,blkid,ssh*,sftp,scp,c_rehash} /sbin/{mount.exfat,mount.ntfs} /usr/sbin/sshd
rm -f /etc/profile.d/motd-bs.sh
rm -rf /usr/etc
# Remove kernel modules
find /opt/bleemsync_kernel -type f -exec rmmod {} \;
rm -rf /opt
# Remove systemd units
systemctl disable ftp.socket
systemctl disable telnet.socket
systemctl disable bleemsync.service
rm -f /etc/systemd/system/{bleemsync.service,ftp.socket,ftp@.service,telnet.socket,telnet@.service,ssh.service}
rm -f /etc/versions/bleemsync_loader.ver /etc/systemd/system/bleemsync_loader.ver
rm -f /data/rndis-mac-address
sed -i "s/iUiUserSettingLastSelectGameCursorPos=.*/iUiUserSettingLastSelectGameCursorPos=0/" /data/AppData/sony/ui/user.pre
#Remove SSH account
sed -i '/^sshd/d' /etc/group
sed -i '/^sshd/d' /etc/passwd
# Restore hostname
echo aiv8167-rockman-emmc > /etc/hostname
# Disable root shell access
passwd -l root
# Revert variant change
if [ "$(cat /etc/hostname)" = "aiv8167-rockman-emmc" ]; then
    echo user > /etc/versions/variant
fi

sync
mount -o remount,ro /
reboot
