#!/bin/sh
#
#  Copyright 2019 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################
# BleemSync Bootloader - CLOSED SOURCE (to prevent people from fucking it up)
# If someone knows how to open the payload and extract this file then
# hopefully they know what to modify and what not to modify!
# ModMyClassic.com / https://discordapp.com/invite/8gygsrw
###############################################################################

source /var/volatile/bleemsync.cfg

if [ -z "$1" ]; then
    echo "usage: $0 <TEXT> <TEXTX> <TEXTY> <FONTSIZE> <FONT> <R> <G> <B> <BGIMAGEPATH> <TEXTBGCOLOR (0xAARRGGBB)> &" 1>&2
    exit 1
fi

#Process Input
text="${1}"
textX="${2}"
textY="${3}"
fontsize="${4}"
font="${5}"
colorR="${6}"
colorG="${7}"
colorB="${8}"
bgimage="${9}"
bgcolor="${10}"
tmpcommand="/tmp/sdldisplaycmd"

#Sanitise Input
if [ ! -z "$text" ]; then
  [ -z "$textX" ] && textX=640
  [ -z "$textY" ] && textY=120
  [ -z "$fontsize" ] && fontsize=12
  [ -z "$font" ] && font=/usr/share/fonts/ttf/LiberationMono-Regular.ttf
  [ -z "$colorR" ] && colorR=255
  [ -z "$colorG" ] && colorG=255
  [ -z "$colorB" ] && colorB=255
fi
[ -z "$bgimage" ] && bgimage="splashscreen.png"

#Create SDL DISPLAY INPUT
echo "IMAGE	640	360	$bgimage" > $tmpcommand
if [ -z "$bgcolor" ]; then
  echo "FTEXT	$textX	$textY	$fontsize	$font	$colorR	$colorG	$colorB	$text" >> $tmpcommand
else
  echo "FTEXTWBG	$textX	$textY	$fontsize	$font	$colorR	$colorG	$colorB	$bgcolor	$text" >> $tmpcommand
fi

#Execute to FrameBuffer and clean up
sdl_display -file $tmpcommand > /dev/null 2>&1 &
