#!/bin/sh
#
#  Copyright 2019 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################
# BleemSync Bootloader - CLOSED SOURCE (to prevent people from fucking it up)
# If someone knows how to open the payload and extract this file then
# hopefully they know what to modify and what not to modify!
# ModMyClassic.com / https://discordapp.com/invite/8gygsrw
###############################################################################

text_x=640
text_y=120
text_size=16
text_font=/usr/share/fonts/ttf/LiberationMono-Regular.ttf
text_bg=0x7E000000
background=splashscreen.png

wait_for_completion(){
    while [ $(pidof $1) ]; do
      echo 0 > /sys/class/leds/green/brightness
      echo 1 > /sys/class/leds/red/brightness
      sleep 1
      echo 1 > /sys/class/leds/green/brightness
      echo 0 > /sys/class/leds/red/brightness
      sleep 1
    done
}

wait_for_completion_no_LED(){
    while [ $(pidof $1) ]; do
      sleep 1
    done
}

log_and_display(){
  echo "[BLEEMSYNC](${1}) ${2}"
  ./sdl_text_display "${2}" $text_x $text_y $text_size $text_font 255 255 255 $background $text_bg
  [ ! -z $3 ] && sleep $3
}

call_reboot(){
  echo 0 > /sys/class/leds/red/brightness
  ./sdl_display "bs_done.png" &
  ./sdl_play "success.wav" &
  echo 0 > /sys/class/leds/green/brightness
  echo 2 > /data/power/disable
  i=1
  while true; do
    echo 1 > /sys/class/leds/red/brightness
    sleep 1 && i=$(( $i + 1 ))
    if [ ! "$i" -le 5 ]; then
    cd /
      sync
      reboot
      break
    fi
    echo 0 > /sys/class/leds/red/brightness
    sleep 1 && i=$(( $i + 1 ))
  done
}
