variables:
  GIT_SUBMODULE_STRATEGY: normal

.build:
  stage: build
  tags:
    - docker
  image: "registry.gitlab.com/cyanic/mmc-kernel-buildenv:latest"
  script:
    - "# package"
    - cp "/build_sup/${PUBKEY}" payload/update/upg_pubk.pem
    - tar xvzf /build_sup/gnupg.tar.gz
    - chmod +x build.sh && chmod +x gpg && ./build.sh payload 5 0
  artifacts:
    paths:
      - out/

dev:
  extends: .build
  variables:
    PUBKEY: dev_pubk.pem


release:
  extends: .build
  variables:
    PUBKEY: rel_pubk.pem
